import {makeStyles} from '@material-ui/core/styles';

// Import CodeUtils from index.js
const useStyles = makeStyles((theme) => ({
  root: {
    position: 'relative',
    height: '100%',
    backgroundColor: '#1a1a1a',
  },
  canvas: {
    display: 'flex',
    height: '100%',
    minHeight: '600px',
    gap: theme.spacing(3),
    padding: theme.spacing(3),
  },
  progress: {
    flex: '0 0 25%',
    height: '100%',
    display: 'flex',
    overflow: 'hidden',
    position: 'relative',
    flexDirection: 'column',
    backgroundColor: '#262626',
    borderRadius: '15px',
    border: '1px solid #404040',
  },
  appBar: {
    borderBottom: 'none',
    position: 'relative',
    backgroundColor: '#262626',
  },
  progressHeader: {
    padding: theme.spacing(0.5),
    backgroundColor: '#262626',
    borderTopLeftRadius: '15px',
    borderTopRightRadius: '15px',
    borderBottom: '1px solid #404040',
  },
  tabContainer: {
    display: 'flex',
    backgroundColor: '#262626',
    padding: '2px',
    borderRadius: '15px',
    border: '1px solid #404040',
  },
  tab: {
    flex: 1,
    padding: theme.spacing(1),
    textAlign: 'center',
    color: '#9ca3af',
    cursor: 'pointer',
    borderRadius: '15px',
    transition: 'all 0.2s ease',
    '& .MuiTypography-root': {
      fontSize: '14px',
      fontWeight: 500,
    },
    '&:hover': {
      backgroundColor: '#333333',
      color: '#ffffff',
    },
  },
  activeTab: {
    backgroundColor: '#333333',
    color: '#ffffff',
  },
  progressContent: {
    flex: 1,
    overflowY: 'auto',
    backgroundColor: '#262626',
    '&::-webkit-scrollbar': {
      width: '4px',
    },
    '&::-webkit-scrollbar-track': {
      background: '#1a1a1a',
    },
    '&::-webkit-scrollbar-thumb': {
      background: '#404040',
      borderRadius: '2px',
      '&:hover': {
        background: '#4a4a4a',
      },
    },
  },
  chatHistory: {
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(3),
    padding: theme.spacing(2.5, 3),
    flex: 1,
    overflowY: 'auto',
    overflowX: 'hidden',
    marginBottom: theme.spacing(2),
    scrollBehavior: 'smooth',
    '&::-webkit-scrollbar': {
      width: '8px',
    },
    '&::-webkit-scrollbar-track': {
      background: '#1a1a1a',
    },
    '&::-webkit-scrollbar-thumb': {
      background: '#404040',
    },
  },
  chatMessage: {
    padding: theme.spacing(2),
    maxWidth: '100%',
    position: 'relative',
    fontSize: '0.95rem',
    lineHeight: 1.6,
    color: '#ffffff',
    '&.user': {
      backgroundColor: '#333333',
      color: '#ffffff',
      alignSelf: 'flex-end',
      marginLeft: 'auto',
      textAlign: 'right',
      borderRadius: '12px',
      padding: theme.spacing(1.5, 2),
    },
    '&.ai': {
      backgroundColor: '#262626',
      color: '#ffffff',
      alignSelf: 'flex-start',
      borderRadius: '12px',
      border: '1px solid #404040',
      padding: theme.spacing(2),
      '&.typing': {
        backgroundColor: '#333333',
        border: 'none',
        '& .MuiTypography-root': {
          color: '#9ca3af',
          fontStyle: 'italic',
        },
      },
      '&.error': {
        borderColor: '#991b1b',
        backgroundColor: '#7f1d1d',
        color: '#fecaca',
      },
    },
  },
  messageWrapper: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    position: 'relative',
    '&.user': {
      justifyContent: 'flex-end',
      maxWidth: '50%',
      width: 'auto',
      alignSelf: 'flex-end',
    },
  },
  messageContent: {
    wordBreak: 'break-word',
    '& .MuiTypography-body1': {
      fontSize: '0.95rem',
      lineHeight: 1.6,
      color: '#1a1a1a',
    },
  },
  inputContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: theme.spacing(2),
    // backgroundColor: '#1e1e1e',
    borderTop: '1px solid rgba(255, 255, 255, 0.1)',
    zIndex: 1,
  },
  input: {
    width: '100%',
    '& .MuiInputBase-input': {
      color: 'rgba(255, 255, 255, 0.9)',
      padding: theme.spacing(1.2, 2),
      '&::placeholder': {
        color: 'rgba(255, 255, 255, 0.5)',
        opacity: 1,
      },
    },
  },
  inputWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1),
    backgroundColor: '#2d2d2d',
    borderRadius: theme.spacing(1),
    padding: theme.spacing(1),
  },
  actionButtons: {
    position: 'absolute',
    right: theme.spacing(3),
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'flex',
    gap: theme.spacing(1),
    '& .MuiIconButton-root': {
      padding: theme.spacing(1),
      transition: 'all 0.2s ease',
      color: '#9ca3af',
      '&:hover': {
        backgroundColor: '#333333',
        color: '#ffffff',
      },
    },
  },
  preview: {
    flex: '0 0 75%',
    display: 'flex',
    padding: '0',
    flexDirection: 'column',
    backgroundColor: '#262626',
    border: '1px solid #404040',
    overflow: 'hidden',
    borderRadius: '15px',
  },
  previewHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#262626',
    borderBottom: '1px solid #404040',
    padding: '4px 8px',
  },
  previewTabs: {
    backgroundColor: '#262626',
    '& .MuiTab-root': {
      color: '#9ca3af',
      '&.Mui-selected': {
        color: '#ffffff',
      },
    },
    '& .MuiTabs-indicator': {
      backgroundColor: '#ffffff',
    },
  },
  previewContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minHeight: 0,
    backgroundColor: '#262626',
  },
  livePreview: {
    width: '100%',
    height: '100%',
    backgroundColor: '#262626',
    '& iframe': {
      backgroundColor: '#262626',
      border: 'none',
    },
  },
  noPreview: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    backgroundColor: '#262626',
    color: '#9ca3af',
  },
  urlBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: theme.spacing(0.5, 1),
    backgroundColor: '#1a1a1a',
    // borderBottom: '1px solid #404040',
    height: '36px',
  },
  urlText: {
    display: 'flex',
    paddingLeft: theme.spacing(2),
    alignItems: 'center',
    gap: theme.spacing(1),
    color: '#9ca3af',
    fontSize: '13px',
    '& .MuiTypography-root': {
      fontSize: '13px',
    },
  },
  urlActions: {
    display: 'flex',
    gap: theme.spacing(0.5),
    '& .MuiIconButton-root': {
      padding: 4,
      color: '#9ca3af',
      '&:hover': {
        color: '#ffffff',
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
      },
    },
  },
  previewFrame: {
    width: '100%',
    height: '100%',
    border: 'none',
    backgroundColor: '#262626',
  },
  nextButton: {
    color: 'white',
    border: 'none',
    padding: '6px 16px',
    position: 'relative',
    fontSize: '1rem',
    minWidth: '120px',
    boxShadow: '0 4px 14px rgba(0, 0, 0, 0.1)',
    fontWeight: 500,
    borderRadius: '10px',
    paddingRight: '5px',
    textTransform: 'none',
    backgroundColor: '#098fdc',
    transition: 'all 0.2s ease-in-out',
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1),
    '&.Mui-disabled': {
      backgroundColor: 'rgba(9, 143, 220, 0.4)',
      color: 'rgba(255, 255, 255, 0.8)',
    },
    '& .MuiSvgIcon-root': {
      fontSize: '1rem',
      marginLeft: theme.spacing(1),
    },
    '&:hover': {
      backgroundColor: '#0076c6',
      transform: 'translateX(4px)',
      boxShadow: '0 6px 20px rgba(0,0,0,0.15)',
      '& .MuiSvgIcon-root': {
        transform: 'translateX(2px)',
      },
    },
  },
  nextButtonWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(2),
  },
  nextInfo: {
    position: 'absolute',
    top: '100%',
    right: 0,
    marginTop: theme.spacing(1),
    padding: theme.spacing(1, 2),
    backgroundColor: 'rgba(9, 143, 220, 0.1)',
    borderRadius: theme.spacing(1),
    fontSize: '0.875rem',
    color: '#098fdc',
    whiteSpace: 'nowrap',
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1),
    '&:before': {
      content: '""',
      position: 'absolute',
      top: -6,
      right: '30%',
      width: 12,
      height: 12,
      backgroundColor: 'rgba(9, 143, 220, 0.1)',
      transform: 'rotate(45deg)',
    },
  },
  tabRoot: {
    minWidth: 'auto',
    padding: '6px 12px',
    textTransform: 'none',
    fontWeight: theme.typography.fontWeightMedium,
    fontSize: '0.875rem',
    '&.Mui-selected': {
      color: '#1a1a1a',
    },
  },
  tabsRoot: {
    minHeight: 'auto',
    borderBottom: `1px solid #f0f0f0`,
  },
  tabsIndicator: {
    backgroundColor: '#1a1a1a',
  },
  livePreview: {
    height: '100%',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
  liveEditor: {
    fontFamily: 'monospace',
    backgroundColor: '#f8fafc',
    borderRadius: '12px',
    marginTop: theme.spacing(2),
    padding: theme.spacing(2),
  },
  liveError: {
    padding: theme.spacing(2),
    color: '#1a1a1a',
    backgroundColor: '#ffebee',
    borderRadius: '12px',
    marginTop: theme.spacing(2),
  },
  chatContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    backgroundColor: '#1e1e1e',
    position: 'relative',
    height: '100%',
  },
  messageList: {
    flex: 1,
    overflowY: 'auto',
    padding: theme.spacing(2),
    paddingBottom: '80px',
    display: 'flex',
    flexDirection: 'column',
  },
  messageIcon: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    backgroundColor: '#f5f5f5',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: theme.spacing(2),
    '& img': {
      width: 24,
      height: 24,
      borderRadius: '50%',
    },
  },
  noPreview: {
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(2),
    color: theme.palette.text.secondary,
    fontSize: '0.95rem',
    padding: theme.spacing(3),
  },
  loadingIcon: {
    width: 24,
    height: 24,
    borderRadius: '50%',
    backgroundColor: '#f5f5f5',
    padding: theme.spacing(0.5),
  },
  slideContainer: {
    position: 'relative',
    height: '100%',
    overflow: 'hidden',
  },
  slidePage: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  confirmDialog: {
    '& .MuiDialog-paper': {
      borderRadius: '12px',
      padding: theme.spacing(2),
    },
  },
  dialogTitle: {
    '& .MuiTypography-root': {
      fontSize: '1.25rem',
      fontWeight: 500,
    },
  },
  dialogContent: {
    padding: theme.spacing(2),
    paddingBottom: theme.spacing(3),
    '& .MuiTypography-root': {
      color: theme.palette.text.secondary,
    },
  },
  dialogActions: {
    padding: theme.spacing(2),
    gap: theme.spacing(1),
  },
  stepHeader: {
    backgroundColor: '#1E1E2E',
    padding: theme.spacing(3),
    borderRadius: theme.spacing(1),
    marginBottom: theme.spacing(3),
  },
  stepTitle: {
    color: '#E4E4E7',
    fontWeight: 500,
  },
  stepDescription: {
    color: '#A1A1AA',
    marginTop: theme.spacing(1),
  },
  activeStep: {
    color: '#64FFDA',
  },
  processingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#FFFFFF',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    minHeight: '500px',
  },
  heartLogo: {
    marginBottom: theme.spacing(6),
    animation: '$pulse 2s infinite',
    width: '80px',
    height: '80px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    '& img': {
      width: '100%',
      height: '100%',
      objectFit: 'contain',
    },
  },
  processingTitle: {
    fontSize: '1.75rem',
    fontWeight: 500,
    marginBottom: theme.spacing(8),
    color: '#1A1A1A',
  },
  processingSteps: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    position: 'relative',
    height: '40px',
    overflow: 'hidden',
    width: '100%',
    maxWidth: '400px',
  },
  processingStep: {
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(2),
    fontSize: '1rem',
    color: '#666',
    fontWeight: 400,
    position: 'absolute',
    transition: 'all 0.5s ease-in-out',
    width: '100%',
    textAlign: 'center',
    justifyContent: 'center',
  },
  activeStep: {
    transform: 'translateY(0)',
    opacity: 1,
  },
  inactiveStep: {
    transform: 'translateY(100%)',
    opacity: 0.3,
  },
  stepIcon: {
    fontSize: '1.25rem',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  '@keyframes pulse': {
    '0%': {
      transform: 'scale(1)',
      opacity: 0.8,
    },
    '50%': {
      transform: 'scale(1.1)',
      opacity: 1,
    },
    '100%': {
      transform: 'scale(1)',
      opacity: 0.8,
    },
  },
  publishButton: {
    position: 'absolute',
    right: theme.spacing(2),
    top: '50%',
    transform: 'translateY(-50%)',
    backgroundColor: '#18181b',
    color: '#fff',
    borderRadius: '8px',
    padding: '6px 16px',
    fontSize: '14px',
    textTransform: 'none',
    fontWeight: 500,
    '&:hover': {
      backgroundColor: '#27272a',
    },
    '& .MuiSvgIcon-root': {
      fontSize: '18px',
      marginRight: theme.spacing(1),
    },
  },
  reviewButton: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#0078d4',
    border: 'none',
    borderRadius: '6px',
    padding: '10px 16px',
    cursor: 'pointer',
    marginBottom: '12px',
    width: 'fit-content',
    transition: 'background-color 0.2s ease',
    '&:hover': {
      backgroundColor: '#006abc',
    },
  },
  reviewCount: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    color: 'white',
    borderRadius: '4px',
    padding: '2px 8px',
    marginRight: '8px',
    fontSize: '12px',
    fontWeight: 500,
  },
  reviewText: {
    color: 'white',
    fontSize: '12px',
    fontWeight: 500,
  },
  reviewNotification: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1e1e1e',
    width: '100%',
    padding: '8px 16px',
    borderRadius: '4px',
    border: '1px solid #333',
  },
  reviewLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  reviewIcon: {
    fontSize: '18px',
    color: '#888',
    marginRight: '4px',
  },
  reviewText: {
    color: '#ffffff',
    fontSize: '13px',
    fontWeight: 400,
  },
  reviewActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  rejectButton: {
    backgroundColor: 'transparent',
    color: '#ffffff',
    border: 'none',
    padding: '4px 12px',
    fontSize: '13px',
    borderRadius: '4px',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
    },
  },
  acceptButton: {
    backgroundColor: '#0078d4',
    color: '#ffffff',
    border: 'none',
    padding: '4px 12px',
    fontSize: '13px',
    borderRadius: '4px',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: '#006abc',
    },
  },
}));

export default useStyles;
